# Generated by Django 4.2.7 on 2024-04-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0003_admin_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='emp',
        ),
    ]
