# Generated by Django 4.2.7 on 2024-04-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
        ('Adm', '0004_remove_admin_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='Emp.emp'),
        ),
    ]
