# Generated by Django 4.2.7 on 2024-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adm', '0005_admin_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
